---
- name: Create users
  hosts: nodes
  vars_files:
    - password.yml
  vars:
    username:
      - Alice
      - Bob
      - Carol
  tasks:
    - name: Create "{{ item }}"
      user:
        name: "{{ item }}"
        comment: "{{ item }}@example.com"
        password: "{{ pwhash | password_hash('sha512') }}" 
        update_password: on_create
      with_items: "{{ username }}"
...
